### ISSUE TITLE
Show metadata

### ISSUE THREAD

**Issue by netgroupgmbh** [heart-bits/contao-article-backgrounds-bundle#2]
Hi,
it would be nice to output the metadata of the image selected as a background.
Could you please add them?
Thanks!

**Comment by saschawustmann** [comment]
Hi @netgroupgmbh,

thanks for you interest in the bundle and your request.
With the 1.1.0 release, you should be able to see the meta data stored in the file system.

Please check this in your project(s) and let me know if everything works!
Thanks

**Comment by netgroupgmbh** [comment]
Hi,
thanks a lot! It works perfectly!
Cheers!
