### ISSUE TITLE
Contao 5 Release?

### ISSUE THREAD

**Issue by theDyingMountain** [heart-bits/contao-article-backgrounds-bundle#3]
Are there any plans for Contao 5 support?

**Comment by saschawustmann** [comment]
@theDyingMountain , thanks for you interest in my extension.
Please try version 2.0.0 whenever you find the time and let me know, if everything works for you!

**Comment by theDyingMountain** [comment]
@saschawustmann thx for the quick reaction. Everything works in my case. But I didn't test the polygon feature.
